"use client";

import React, { useState } from "react";
import { Copy, Check, Download, Printer } from "lucide-react";

interface AIExportToolbarProps {
  title: string;
  content: string;
}

export default function AIExportToolbar({ title, content }: AIExportToolbarProps) {
  const [copied, setCopied] = useState(false);

  if (!content) return null;

  function handleCopy() {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function handleDownloadTXT() {
    const blob = new Blob([`${title.toUpperCase()}\nGenerated by LifeOS AI Platform\nDate: ${new Date().toLocaleDateString()}\n\n${content}`], {
      type: "text/plain;charset=utf-8",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.toLowerCase().replace(/\s+/g, "_")}_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function handlePrintPDF() {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${title} - LifeOS Report</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; padding: 40px; color: #1e293b; max-width: 800px; margin: 0 auto; }
            h1 { color: #0f172a; border-b: 2px solid #e2e8f0; padding-bottom: 10px; font-size: 24px; }
            .meta { color: #64748b; font-size: 12px; margin-bottom: 24px; }
            pre { white-space: pre-wrap; font-family: inherit; line-height: 1.6; font-size: 14px; }
            table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 13px; }
            th, td { border: 1px solid #cbd5e1; padding: 8px 12px; text-align: left; }
            th { background-color: #f1f5f9; }
          </style>
        </head>
        <body>
          <h1>${title}</h1>
          <div class="meta">LifeOS AI Platform | Date: ${new Date().toLocaleString()}</div>
          <pre>${content.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</pre>
          <script>
            window.onload = function() { window.print(); };
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  }

  return (
    <div className="flex items-center justify-between gap-2 p-2 px-3 bg-slate-100/90 border border-slate-200 rounded-xl text-xs font-medium text-slate-700 my-3">
      <span className="text-slate-500 font-semibold flex items-center gap-1.5">
        Export Options:
      </span>
      <div className="flex items-center gap-1.5">
        <button
          onClick={handleCopy}
          className="flex items-center gap-1 px-2.5 py-1 bg-white hover:bg-slate-50 border border-slate-200 rounded-lg text-slate-700 transition shadow-2xs"
          title="Copy report text"
        >
          {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 text-slate-500" />}
          {copied ? "Copied!" : "Copy"}
        </button>
        <button
          onClick={handleDownloadTXT}
          className="flex items-center gap-1 px-2.5 py-1 bg-white hover:bg-slate-50 border border-slate-200 rounded-lg text-slate-700 transition shadow-2xs"
          title="Download TXT file"
        >
          <Download className="w-3.5 h-3.5 text-slate-500" />
          TXT
        </button>
        <button
          onClick={handlePrintPDF}
          className="flex items-center gap-1 px-2.5 py-1 bg-white hover:bg-slate-50 border border-slate-200 rounded-lg text-slate-700 transition shadow-2xs"
          title="Print / Save PDF"
        >
          <Printer className="w-3.5 h-3.5 text-slate-500" />
          PDF
        </button>
      </div>
    </div>
  );
}
