import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/auth";
import { ChatOpenAI } from "@langchain/openai";

export const dynamic = "force-dynamic";

const rateLimitMap = new Map<string, { count: number; resetTime: number }>();

function checkRateLimit(ip: string): boolean {
  const now = Date.now();
  const windowMs = 60 * 1000; // 1 minute
  const maxRequests = 10;

  const record = rateLimitMap.get(ip);
  if (!record || now > record.resetTime) {
    rateLimitMap.set(ip, { count: 1, resetTime: now + windowMs });
    return true;
  }
  if (record.count >= maxRequests) {
    return false;
  }
  record.count += 1;
  return true;
}

const MEDICAL_DISCLAIMER = "IMPORTANT NOTICE: This AI Symptom Assessment is generated by an automated language model for informational purposes only and DOES NOT constitute a professional medical diagnosis, clinical advice, or treatment plan. If you are experiencing a life-threatening emergency or severe symptoms, please immediately call Emergency Services or consult a licensed physician.";

export async function POST(req: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const ip = req.headers.get("x-forwarded-for") || "127.0.0.1";
    if (!checkRateLimit(ip)) {
      return NextResponse.json({ error: "Too many symptom evaluation requests. Please wait a minute." }, { status: 429 });
    }

    const body = await req.json().catch(() => ({}));
    const { symptoms } = body;

    if (!symptoms || typeof symptoms !== "string" || !symptoms.trim()) {
      return NextResponse.json({ error: "Symptom description is required." }, { status: 400 });
    }

    const chatModel = new ChatOpenAI({
      modelName: "llama-3.3-70b-versatile",
      openAIApiKey: process.env.GROQ_API_KEY,
      configuration: {
        baseURL: "https://api.groq.com/openai/v1",
      },
      temperature: 0.2,
    });

    const systemPrompt = `You are an AI Clinical Triage Assistant. Analyze the user's reported symptoms and return a structured assessment in STRICT JSON format with the following keys:
    - urgency: "Low" | "Medium" | "High" | "Emergency"
    - summary: string (2 sentence overview of symptoms)
    - possibleCauses: string[] (array of 2-4 potential non-conclusive conditions)
    - recommendedSpecialist: string (e.g. "Cardiologist", "General Physician", "Neurologist")
    - nextSteps: string[] (array of 2-3 safe next action steps)
    - medicalDisclaimer: string (must state this is not a diagnosis)

    Return ONLY a valid JSON object matching this schema.`;

    const response = await chatModel.invoke([
      ["system", systemPrompt],
      ["human", symptoms],
    ]);

    let parsed = null;
    try {
      const jsonMatch = response.content.toString().match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        parsed = JSON.parse(jsonMatch[0]);
      } else {
        parsed = JSON.parse(response.content.toString());
      }
    } catch {
      console.warn("[Symptom Checker] JSON parse failure, using structured fallback");
      parsed = {
        urgency: "Unknown — Assessment Incomplete",
        summary: "We could not automatically determine a clinical triage assessment for your description. Please consult a healthcare professional directly.",
        possibleCauses: ["Requires direct physician examination"],
        recommendedSpecialist: "General Physician / Primary Care Provider",
        nextSteps: ["Schedule an in-person consultation with a licensed physician"],
        medicalDisclaimer: MEDICAL_DISCLAIMER,
        assessmentCompleted: false,
      };
    }

    // Always enforce non-diagnostic disclaimer in response
    parsed.disclaimer = MEDICAL_DISCLAIMER;

    return NextResponse.json({
      success: true,
      assessment: parsed,
    });
  } catch (error) {
    console.error("Symptom Checker API Error:", error);
    return NextResponse.json({ error: "Failed to evaluate symptoms." }, { status: 500 });
  }
}
